// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmwmer3d-uDZI3ktK70eAFTwBF5EkaLUM',
    appId: '1:1070896902617:web:dcd815f151a24769fc69c8',
    messagingSenderId: '1070896902617',
    projectId: 'bankapp-5d654',
    authDomain: 'bankapp-5d654.firebaseapp.com',
    storageBucket: 'bankapp-5d654.firebasestorage.app',
    measurementId: 'G-R1STZND2VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBEoURlASPCAB6jVvjkJLiEuyGQwaEvc',
    appId: '1:1070896902617:android:9388068a47aefa64fc69c8',
    messagingSenderId: '1070896902617',
    projectId: 'bankapp-5d654',
    storageBucket: 'bankapp-5d654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkpk_fk5rwd-DDz2iOguRBS6XfUsWOUw',
    appId: '1:1070896902617:ios:4450da963fe003e5fc69c8',
    messagingSenderId: '1070896902617',
    projectId: 'bankapp-5d654',
    storageBucket: 'bankapp-5d654.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnkpk_fk5rwd-DDz2iOguRBS6XfUsWOUw',
    appId: '1:1070896902617:ios:4450da963fe003e5fc69c8',
    messagingSenderId: '1070896902617',
    projectId: 'bankapp-5d654',
    storageBucket: 'bankapp-5d654.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmwmer3d-uDZI3ktK70eAFTwBF5EkaLUM',
    appId: '1:1070896902617:web:29e6fe244b66ad18fc69c8',
    messagingSenderId: '1070896902617',
    projectId: 'bankapp-5d654',
    authDomain: 'bankapp-5d654.firebaseapp.com',
    storageBucket: 'bankapp-5d654.firebasestorage.app',
    measurementId: 'G-JS8Z29W4SL',
  );
}
